title: Notes
description: 个人笔记
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "mint"

url: https://itflash.github.io
baseurl: /notes

author:
  name: "itflash"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
  - scope:
      path: ""
    values:
      layout: single

search: true

plugins:
  - jekyll-include-cache
