title: Notes
tagline: 个人笔记
description: 个人笔记库
theme: jekyll-theme-chirpy

url: "https://itflash.github.io"
baseurl: "/notes"

author: "itflash"

theme_mode: light

defaults:
  - scope:
      path: "_posts"
    values:
      layout: post
  - scope:
      path: ""
    values:
      layout: page

toc: true

sass:
  sass_dir: _sass
  style: compressed

jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
